Test/aux 0002
NadinaJauch/be_java_hisp_w28_g07 pull request #63
Opened 2024-12-30 20:13 UTC by lvingman

Agrega validaciones.
Habria que ver como encarar validaciones para userId y productId (ie: reescribir ints a Integer)

2024-12-30 20:20 UTC, lisandroaloo approved these changes

2024-12-30 20:34 UTC, martinsimonetti requested changes
@Min(value = -1, message = "El id debe ser mayor a cero")
El valor en estás líneas, deberían ser 1.

2024-12-30 20:48 UTC, lvingman commented
> @min(value = -1, message = "El id debe ser mayor a cero") El valor en estás líneas, deberían ser 1.

Lo voy a hacer una vez que mergeen este PR a dev: https://github.com/NadinaJauch/be_java_hisp_w28_g07/pull/65

2025-01-02 13:08 UTC, lvingman commented
Actualize la rama, elimine ciertas dependencias en el pom que no permitian la validacion de objetos, principalmente Javax y Hibernate validate.

Considerar que agregar y que no en el merge review

2025-01-02 14:37 UTC, NadinaJauch approved these changes

2025-01-02 14:39 UTC, martinsimonetti approved these changes

2025-01-02 14:41 UTC, merged