Se realizó el test de listas de Followers y Followeds. Ordenamiento erroneo.
NadinaJauch/be_java_hisp_w28_g07 pull request #64
Opened 2024-12-30 20:26 UTC by martinsimonetti

2024-12-31 19:49 UTC, martinsimonetti commented
Terminé de realizar el caso de prueba con los casos de éxito y los que tiraban la excepción. Deberían revisar y aprobar para poder agregar los cambios. Muchas gracias.

2025-01-02 12:37 UTC, lisandroaloo requested changes

2025-01-02 12:37 UTC, lisandroaloo commented on social-meli/src/test/java/com/api/social_meli/unit/service/UserServiceTest.java
> +        //Arrange
No creo que sea necesario hacer el orden invalido al reves, con el primero ya es suficiente, porque se entiende que tiene que ser o name_desc o name_asc

2025-01-02 13:18 UTC, martinsimonetti commented on social-meli/src/test/java/com/api/social_meli/unit/service/UserServiceTest.java
> +        //Arrange
Licha, no te entiendo lo del "el orden invalido al reves". El caso de prueba pide "Verificar que el tipo de ordenamiento alfabético exista (US-0008)".
Se cumple: Permite continuar con normalidad.
No se cumple: Notifica la no existencia mediante una excepción.
Me pidieron hacer caso de éxito y caso que no. Eso al menos dijo Joy.

2025-01-02 15:23 UTC, lisandroaloo approved these changes

2025-01-02 15:23 UTC, NadinaJauch approved these changes

2025-01-02 15:23 UTC, merged